# coding: utf-8

"""
    Core Operations

    The Sparkfly Platform provides a full lifecycle for promotions and rewards from creation to distribution to settlement. The platform integrates in real-time at the point-of-sale and provides item level discounting and tracking. The capabilities of the Sparkfly Platform are available through the use of the Sparkfly Platform API.  The Sparkfly documentation site is under development. If the documentation you're after isn't available here, please contact support@sparkfly.com and we will get you what you need.

    The version of the OpenAPI document: 1.0
    Contact: support@sparkfly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sparkfly.models.member_all_of_member_credential import MemberAllOfMemberCredential

class TestMemberAllOfMemberCredential(unittest.TestCase):
    """MemberAllOfMemberCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemberAllOfMemberCredential:
        """Test MemberAllOfMemberCredential
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemberAllOfMemberCredential`
        """
        model = MemberAllOfMemberCredential()
        if include_optional:
            return MemberAllOfMemberCredential(
                id = 56,
                identifier = '',
                type = '',
                channel_id = 56
            )
        else:
            return MemberAllOfMemberCredential(
        )
        """

    def testMemberAllOfMemberCredential(self):
        """Test MemberAllOfMemberCredential"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
