# coding: utf-8

"""
    Core Operations

    The Sparkfly Platform provides a full lifecycle for promotions and rewards from creation to distribution to settlement. The platform integrates in real-time at the point-of-sale and provides item level discounting and tracking. The capabilities of the Sparkfly Platform are available through the use of the Sparkfly Platform API.  The Sparkfly documentation site is under development. If the documentation you're after isn't available here, please contact support@sparkfly.com and we will get you what you need.

    The version of the OpenAPI document: 1.0
    Contact: support@sparkfly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sparkfly.models.credential_index_body import CredentialIndexBody

class TestCredentialIndexBody(unittest.TestCase):
    """CredentialIndexBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialIndexBody:
        """Test CredentialIndexBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialIndexBody`
        """
        model = CredentialIndexBody()
        if include_optional:
            return CredentialIndexBody(
                page = 56,
                per_page = 56,
                total_entries = 56,
                total_pages = 56,
                credentials = [
                    sparkfly.models.credential_index_body_inner.credential_index_body_inner(
                        credential = sparkfly.models.credential_index_body_inner_credential.credential_index_body_inner_credential(
                            id = 56, 
                            identifier = '', 
                            member_id = 56, 
                            account_id = 56, 
                            redeeming_account_id = 56, 
                            channel_id = 56, 
                            eligible_channel_id = 56, 
                            store_id = 56, 
                            voided_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            redeemed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            processed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reusable = True, 
                            locked = True, 
                            url = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            type = 'offer', 
                            offer_ids = [
                                56
                                ], 
                            merchant_id = 56, 
                            merchant_name = '', 
                            offer_name = '', 
                            location_address = '', 
                            supports_barcode = True, 
                            barcodes_supported = '', ), 
                        errors = sparkfly.models.errors.errors(), )
                    ]
            )
        else:
            return CredentialIndexBody(
        )
        """

    def testCredentialIndexBody(self):
        """Test CredentialIndexBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
