# coding: utf-8

"""
    Core Operations

    The Sparkfly Platform provides a full lifecycle for promotions and rewards from creation to distribution to settlement. The platform integrates in real-time at the point-of-sale and provides item level discounting and tracking. The capabilities of the Sparkfly Platform are available through the use of the Sparkfly Platform API.  The Sparkfly documentation site is under development. If the documentation you're after isn't available here, please contact support@sparkfly.com and we will get you what you need.

    The version of the OpenAPI document: 1.0
    Contact: support@sparkfly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from sparkfly.models.credential_create_request import CredentialCreateRequest
from sparkfly.models.credential_create_response import CredentialCreateResponse
from sparkfly.models.credential_index_body import CredentialIndexBody

from sparkfly.api_client import ApiClient, RequestSerialized
from sparkfly.api_response import ApiResponse
from sparkfly.rest import RESTResponseType


class CredentialsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def create_credential(
        self,
        content_type: Annotated[Optional[StrictStr], Field(description="application/json")] = None,
        credential_create_request: Optional[CredentialCreateRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CredentialCreateResponse:
        """Create a Credential

        Creates a new credential for a member, which can be used to redeem offers or participate in loyalty programs.

        :param content_type: application/json
        :type content_type: str
        :param credential_create_request:
        :type credential_create_request: CredentialCreateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_credential_serialize(
            content_type=content_type,
            credential_create_request=credential_create_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialCreateResponse",
            '401': None,
            '422': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def create_credential_with_http_info(
        self,
        content_type: Annotated[Optional[StrictStr], Field(description="application/json")] = None,
        credential_create_request: Optional[CredentialCreateRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CredentialCreateResponse]:
        """Create a Credential

        Creates a new credential for a member, which can be used to redeem offers or participate in loyalty programs.

        :param content_type: application/json
        :type content_type: str
        :param credential_create_request:
        :type credential_create_request: CredentialCreateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_credential_serialize(
            content_type=content_type,
            credential_create_request=credential_create_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialCreateResponse",
            '401': None,
            '422': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def create_credential_without_preload_content(
        self,
        content_type: Annotated[Optional[StrictStr], Field(description="application/json")] = None,
        credential_create_request: Optional[CredentialCreateRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create a Credential

        Creates a new credential for a member, which can be used to redeem offers or participate in loyalty programs.

        :param content_type: application/json
        :type content_type: str
        :param credential_create_request:
        :type credential_create_request: CredentialCreateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_credential_serialize(
            content_type=content_type,
            credential_create_request=credential_create_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialCreateResponse",
            '401': None,
            '422': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_credential_serialize(
        self,
        content_type,
        credential_create_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter
        if credential_create_request is not None:
            _body_params = credential_create_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'XAuthToken'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/credentials',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def search_credentials(
        self,
        identifier: Annotated[Optional[StrictStr], Field(description="The credential identifier to search for (e.g., a phone number, email, or external ID).")] = None,
        member_id: Annotated[Optional[StrictInt], Field(description="Return all credentials attached to this Sparkfly member.")] = None,
        store_id: Annotated[Optional[StrictInt], Field(description="Filter by store ID.")] = None,
        channel_id: Annotated[Optional[StrictStr], Field(description="Filter by channel ID.")] = None,
        ids: Annotated[Optional[List[StrictInt]], Field(description="Filter by specific credential IDs.")] = None,
        redeemed: Annotated[Optional[StrictBool], Field(description="Only return credentials that have / have not been redeemed.")] = None,
        inactive_later_than: Annotated[Optional[StrictStr], Field(description="Return credentials inactive after this timestamp.")] = None,
        offer_id: Annotated[Optional[StrictStr], Field(description="Filter by offer ID.")] = None,
        eligible_channel_id: Annotated[Optional[StrictInt], Field(description="Filter by eligible channel ID.")] = None,
        reusable: Annotated[Optional[StrictBool], Field(description="Filter by reusable flag.")] = None,
        credential_type: Annotated[Optional[StrictInt], Field(description="Filter by credential type.")] = None,
        page: Annotated[Optional[StrictStr], Field(description="Page offset to display a range of records from.")] = None,
        per_page: Annotated[Optional[StrictStr], Field(description="Maximum number of records to return in the search.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CredentialIndexBody:
        """Search Credentials

        Retrieve credentials matching the provided filters. All parameters are optional and may be combined. Common uses: lookup by identifier (e.g., phone/email/external ID) or enumerate every credential attached to a specific member via `member_id`. A single identifier may match multiple credentials over time (e.g., when a credential is voided and reissued to another member). Callers should treat any credential with a non-null `voided_at` as inactive. 

        :param identifier: The credential identifier to search for (e.g., a phone number, email, or external ID).
        :type identifier: str
        :param member_id: Return all credentials attached to this Sparkfly member.
        :type member_id: int
        :param store_id: Filter by store ID.
        :type store_id: int
        :param channel_id: Filter by channel ID.
        :type channel_id: str
        :param ids: Filter by specific credential IDs.
        :type ids: List[int]
        :param redeemed: Only return credentials that have / have not been redeemed.
        :type redeemed: bool
        :param inactive_later_than: Return credentials inactive after this timestamp.
        :type inactive_later_than: str
        :param offer_id: Filter by offer ID.
        :type offer_id: str
        :param eligible_channel_id: Filter by eligible channel ID.
        :type eligible_channel_id: int
        :param reusable: Filter by reusable flag.
        :type reusable: bool
        :param credential_type: Filter by credential type.
        :type credential_type: int
        :param page: Page offset to display a range of records from.
        :type page: str
        :param per_page: Maximum number of records to return in the search.
        :type per_page: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_credentials_serialize(
            identifier=identifier,
            member_id=member_id,
            store_id=store_id,
            channel_id=channel_id,
            ids=ids,
            redeemed=redeemed,
            inactive_later_than=inactive_later_than,
            offer_id=offer_id,
            eligible_channel_id=eligible_channel_id,
            reusable=reusable,
            credential_type=credential_type,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialIndexBody",
            '401': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def search_credentials_with_http_info(
        self,
        identifier: Annotated[Optional[StrictStr], Field(description="The credential identifier to search for (e.g., a phone number, email, or external ID).")] = None,
        member_id: Annotated[Optional[StrictInt], Field(description="Return all credentials attached to this Sparkfly member.")] = None,
        store_id: Annotated[Optional[StrictInt], Field(description="Filter by store ID.")] = None,
        channel_id: Annotated[Optional[StrictStr], Field(description="Filter by channel ID.")] = None,
        ids: Annotated[Optional[List[StrictInt]], Field(description="Filter by specific credential IDs.")] = None,
        redeemed: Annotated[Optional[StrictBool], Field(description="Only return credentials that have / have not been redeemed.")] = None,
        inactive_later_than: Annotated[Optional[StrictStr], Field(description="Return credentials inactive after this timestamp.")] = None,
        offer_id: Annotated[Optional[StrictStr], Field(description="Filter by offer ID.")] = None,
        eligible_channel_id: Annotated[Optional[StrictInt], Field(description="Filter by eligible channel ID.")] = None,
        reusable: Annotated[Optional[StrictBool], Field(description="Filter by reusable flag.")] = None,
        credential_type: Annotated[Optional[StrictInt], Field(description="Filter by credential type.")] = None,
        page: Annotated[Optional[StrictStr], Field(description="Page offset to display a range of records from.")] = None,
        per_page: Annotated[Optional[StrictStr], Field(description="Maximum number of records to return in the search.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CredentialIndexBody]:
        """Search Credentials

        Retrieve credentials matching the provided filters. All parameters are optional and may be combined. Common uses: lookup by identifier (e.g., phone/email/external ID) or enumerate every credential attached to a specific member via `member_id`. A single identifier may match multiple credentials over time (e.g., when a credential is voided and reissued to another member). Callers should treat any credential with a non-null `voided_at` as inactive. 

        :param identifier: The credential identifier to search for (e.g., a phone number, email, or external ID).
        :type identifier: str
        :param member_id: Return all credentials attached to this Sparkfly member.
        :type member_id: int
        :param store_id: Filter by store ID.
        :type store_id: int
        :param channel_id: Filter by channel ID.
        :type channel_id: str
        :param ids: Filter by specific credential IDs.
        :type ids: List[int]
        :param redeemed: Only return credentials that have / have not been redeemed.
        :type redeemed: bool
        :param inactive_later_than: Return credentials inactive after this timestamp.
        :type inactive_later_than: str
        :param offer_id: Filter by offer ID.
        :type offer_id: str
        :param eligible_channel_id: Filter by eligible channel ID.
        :type eligible_channel_id: int
        :param reusable: Filter by reusable flag.
        :type reusable: bool
        :param credential_type: Filter by credential type.
        :type credential_type: int
        :param page: Page offset to display a range of records from.
        :type page: str
        :param per_page: Maximum number of records to return in the search.
        :type per_page: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_credentials_serialize(
            identifier=identifier,
            member_id=member_id,
            store_id=store_id,
            channel_id=channel_id,
            ids=ids,
            redeemed=redeemed,
            inactive_later_than=inactive_later_than,
            offer_id=offer_id,
            eligible_channel_id=eligible_channel_id,
            reusable=reusable,
            credential_type=credential_type,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialIndexBody",
            '401': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def search_credentials_without_preload_content(
        self,
        identifier: Annotated[Optional[StrictStr], Field(description="The credential identifier to search for (e.g., a phone number, email, or external ID).")] = None,
        member_id: Annotated[Optional[StrictInt], Field(description="Return all credentials attached to this Sparkfly member.")] = None,
        store_id: Annotated[Optional[StrictInt], Field(description="Filter by store ID.")] = None,
        channel_id: Annotated[Optional[StrictStr], Field(description="Filter by channel ID.")] = None,
        ids: Annotated[Optional[List[StrictInt]], Field(description="Filter by specific credential IDs.")] = None,
        redeemed: Annotated[Optional[StrictBool], Field(description="Only return credentials that have / have not been redeemed.")] = None,
        inactive_later_than: Annotated[Optional[StrictStr], Field(description="Return credentials inactive after this timestamp.")] = None,
        offer_id: Annotated[Optional[StrictStr], Field(description="Filter by offer ID.")] = None,
        eligible_channel_id: Annotated[Optional[StrictInt], Field(description="Filter by eligible channel ID.")] = None,
        reusable: Annotated[Optional[StrictBool], Field(description="Filter by reusable flag.")] = None,
        credential_type: Annotated[Optional[StrictInt], Field(description="Filter by credential type.")] = None,
        page: Annotated[Optional[StrictStr], Field(description="Page offset to display a range of records from.")] = None,
        per_page: Annotated[Optional[StrictStr], Field(description="Maximum number of records to return in the search.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search Credentials

        Retrieve credentials matching the provided filters. All parameters are optional and may be combined. Common uses: lookup by identifier (e.g., phone/email/external ID) or enumerate every credential attached to a specific member via `member_id`. A single identifier may match multiple credentials over time (e.g., when a credential is voided and reissued to another member). Callers should treat any credential with a non-null `voided_at` as inactive. 

        :param identifier: The credential identifier to search for (e.g., a phone number, email, or external ID).
        :type identifier: str
        :param member_id: Return all credentials attached to this Sparkfly member.
        :type member_id: int
        :param store_id: Filter by store ID.
        :type store_id: int
        :param channel_id: Filter by channel ID.
        :type channel_id: str
        :param ids: Filter by specific credential IDs.
        :type ids: List[int]
        :param redeemed: Only return credentials that have / have not been redeemed.
        :type redeemed: bool
        :param inactive_later_than: Return credentials inactive after this timestamp.
        :type inactive_later_than: str
        :param offer_id: Filter by offer ID.
        :type offer_id: str
        :param eligible_channel_id: Filter by eligible channel ID.
        :type eligible_channel_id: int
        :param reusable: Filter by reusable flag.
        :type reusable: bool
        :param credential_type: Filter by credential type.
        :type credential_type: int
        :param page: Page offset to display a range of records from.
        :type page: str
        :param per_page: Maximum number of records to return in the search.
        :type per_page: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_credentials_serialize(
            identifier=identifier,
            member_id=member_id,
            store_id=store_id,
            channel_id=channel_id,
            ids=ids,
            redeemed=redeemed,
            inactive_later_than=inactive_later_than,
            offer_id=offer_id,
            eligible_channel_id=eligible_channel_id,
            reusable=reusable,
            credential_type=credential_type,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CredentialIndexBody",
            '401': None,
            '500': None,
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_credentials_serialize(
        self,
        identifier,
        member_id,
        store_id,
        channel_id,
        ids,
        redeemed,
        inactive_later_than,
        offer_id,
        eligible_channel_id,
        reusable,
        credential_type,
        page,
        per_page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'ids': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if identifier is not None:
            
            _query_params.append(('identifier', identifier))
            
        if member_id is not None:
            
            _query_params.append(('member_id', member_id))
            
        if store_id is not None:
            
            _query_params.append(('store_id', store_id))
            
        if channel_id is not None:
            
            _query_params.append(('channel_id', channel_id))
            
        if ids is not None:
            
            _query_params.append(('ids', ids))
            
        if redeemed is not None:
            
            _query_params.append(('redeemed', redeemed))
            
        if inactive_later_than is not None:
            
            _query_params.append(('inactive_later_than', inactive_later_than))
            
        if offer_id is not None:
            
            _query_params.append(('offer_id', offer_id))
            
        if eligible_channel_id is not None:
            
            _query_params.append(('eligible_channel_id', eligible_channel_id))
            
        if reusable is not None:
            
            _query_params.append(('reusable', reusable))
            
        if credential_type is not None:
            
            _query_params.append(('credential_type', credential_type))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'XAuthToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/credentials',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


